env:
  global:
  - REPO_DIR=faiss
  - WHEEL_SDIR=dist
  - BUILD_COMMIT=v1.6.1
  - BUILD_DEPENDS="numpy==1.15.0"
  - TEST_DEPENDS="numpy==1.15.0"
  - PLAT=x86_64
  - UNICODE_WIDTH=32
language: python
python: 3.5
dist: trusty
services: docker
matrix:
  exclude:
  - python: 3.5
  include:
  # mac wheels
  - os: osx
    language: generic
    env:
    - MB_PYTHON_VERSION=3.5
  - os: osx
    language: generic
    env:
    - MB_PYTHON_VERSION=3.6
  - os: osx
    language: generic
    env:
    - MB_PYTHON_VERSION=3.7
  - os: osx
    language: generic
    env:
    - MB_PYTHON_VERSION=3.8
  # manylinux1 wheels
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.5
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.6
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.7
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.8
  # manylinux2010 wheels
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.5
    - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.6
    - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.7
    - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.8
    - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
  # manylinux2010 + cuda 9.0 wheels
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.5
    - CUDA_VERSION=9.0
    - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.6
    - CUDA_VERSION=9.0
    - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.7
    - CUDA_VERSION=9.0
    - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.8
    - CUDA_VERSION=9.0
    - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
before_install:
- source multibuild/common_utils.sh
- source multibuild/travis_steps.sh
- before_install
install:
- clean_code $REPO_DIR $BUILD_COMMIT
- mv $REPO_DIR/python/swigfaiss.swig $REPO_DIR/python/swigfaiss.i
- mv $REPO_DIR/python/faiss.py $REPO_DIR/python/__init__.py
- if [ -n "$CUDA_VERSION" ]; then
    cat conf/cuda${CUDA_VERSION}.sh >> env_vars.sh;
    export BUILD_CUDA=True;
  fi
- pip install j2cli && j2 setup.py --undefined > $REPO_DIR/setup.py
- build_wheel $REPO_DIR $PLAT
script:
- install_run $PLAT
before_deploy:
- cd $REPO_DIR
- ln -s ../$WHEEL_SDIR dist
- if [ "$TRAVIS_OS_NAME" == "osx" -a "$MB_PYTHON_VERSION" == "3.5" ]; then
    pip install -U pyOpenSSL;
  fi
deploy:
  provider: pypi
  user: kyamagu
  password:
    secure: fmbjmdhG0wkczVB8sJQwB7RbccVV3hN8fO4x/QwbTIlwQvnRd1XDKANTXn8NORdiJMeTTcJ21qNudjYOSCgC3gg9kbOA2b/mYycFMOcSXLLWOuO3AZHYrAq2KZmB+BX3Scsb1StjUNy4rHV64vk22JK8vx3TmHJDZ2GtmitmJ4qITkxn8EJqsD++e40iUw83GYNuL57Gj2G6XF0kCqUONYWCt+Fk4rjExce+dORzQLHYpr2Owinus5Y34nV1adZmML+L+KZw9kKVHGNC9/UGyT2REz0c8Ei3Jvt5xfoLcJB6lMlK2XS+p7KOO/tgRXB9i7KFej7TUsX0QtgnIpg9AS9c783F+pzh4upKt72McwR8wbUQwJ71pKSuZWgxrKjnXXJpo72Qtu667BSKN2TQjjSnb3wwEECOCCYSAw1fVXjjKo2fnyRsYtdttDDDbvrp+Y7imAgVK0NyUCAxEpYjofkZDF6EHLa5f2+2VVyDPFK1qdiK02uxGHObtMfDFyzzRs4IZEwPIuas98wkiEWp3uP2mY/wG24LgVClKe5jc/JuhUhr6nXdQnVDQNn4TyUTImWoh+4rnYxMMgLvJ+7b0ZFRkdlAowKOznyUxZ04zSXpSjsa0S14gPt5/L5dqka2SprmKe6IUjMfHTetRS23VZPQWcxPeTeO5sWd/2gf5YM=
  skip_cleanup: true
  skip_existing: true
  on:
    tags: true
  distributions: sdist
